### PR TITLE
Minimal updates to get the lessons working with gl-matrix-2.2.1

### PR DESCRIPTION
**Pull request by erictheise**
@tparisi, I realize the repo has outstanding pull requests that do some of what mine does.

In going through the lessons, I had the impulse to update the glMatrix library, thinking I might learn from the experience. Having done it, I have to say, the experience had very little educational value, and there's no reason to put others through it. I've updated the code, making minimal changes, and flagging them, so that someone following the old lessons can clearly see what's changed as a result of upgrading from glMatrix-0.9.5 to gl-matrix-2.2.1.

I've done a little JavaScript cleanup, adding semicolons, removing commas at the end of arrays, and replacing `= Array();` with `= [];` in two or three instances. I've adjusted z values to approximate the composition of the original lessons.

My changes are outlined in UPDATES.txt. There remain issues, such as duplicate variable declarations. Perhaps in the future, someone will jshint all this code, but that's beyond the scope of what I'll tackle at this time.

### CODE REVIEW

**Comment by chaliy** [comment]
Almost a year... it is still not merged :(, it shouldn't be that hard

**Comment by erictheise** [comment]
Appreciate the comment, @chaliy, thanks.

@tparisi's active promoting other projects around the San Francisco Bay Area these days and, not having merged a single pull request in the two years since he's taken over this repo, it seems he's just starving it in hope it'll go away.

**Comment by sallyx** [comment]
well done

**Comment by tparisi** [comment]
Merged.

But the problem is I need to update all the text in the lessons.... _that's_ what I've never had time for. Got it?

**Pull request merged**
